---
title: "Machine Learning Projects"
site: rmarkdown::default_site_generator

---

This site is a portfolio of projects related to tabular machine learning.

Its objective is to provide examples of workflows that enable predicting *something* from high dimensional data.

**Projects**: machine learning workflows (in R) are provided based on existing publications by other research groups. In most cases, analyses are validated and extended.

 - [Microbial Load Predictor](https://pdobrano25.github.io/ml_website/mlp_validation.html): Validating the performance of a novel tool that predicts the number of bacterial cells in a metagenomic sample. A regression problem with internal and external validation. *Additional models* are evaluated.
 - [Predicting Crohn's Disease (Microbiome)](https://pdobrano25.github.io/ml_website/gevers_validation.html): Validating a study from 2014 using (low biomass) microbiome samples obtained from biopsies in new-onset Crohn's disease. Results could not be validated for any discernible reason. Only internal validation was employed. *Additional models* are evaluated.
 - [Predicting IBD (Microbiome)](https://pdobrano25.github.io/ml_website/cmd_validation.html): Validating a meta-analysis from 2023 using stool microbiome samples obtained from 3 cohorts in the curatedMetagenomicData. 3 other cohorts were not available to download, so results could not be fully validated. *Hybrid up/down sampling* is applied. *Additional models* are evaluated.
 - [Predicting IBD (RNAseq)](https://pdobrano25.github.io/ml_website/sinai_validation.html): Re-analyzing a large RNAseq dataset obtained from mucosal biopsies of CD, UC, and non-IBD controls. Focusing on rectum biopsies, applying machine learning to predict inflamed vs non-inflamed samples, and then predicting IBD using non-inflamed samples. *Downsampling* and *ensemble learning* are applied.
 - [Predicting Disease (Microbiome)](https://pdobrano25.github.io/ml_website/metaaml_validation.html): Validating a meta-analysis of microbiome data linked to several different diseases. *Downsampling* and *multiclass learning* are applied, and *additional models* are evaluated.
  - [Predicting IBD (Microbiome)](https://pdobrano25.github.io/ml_website/hmp_validation.html): Validating a metabolomic analysis of microbiome data from IBD and non-IBD subjects. *Downsampling* is applied and *additional models* are evaluated. *Feature importances* are extracted and contextualized with the literature.
  
[**Overfit Check**](https://pdobrano25.github.io/ml_website/overfitcheck.html): comments on poor machine learning engineering leading to **overfitting**.

[**Models**](https://pdobrano25.github.io/ml_website/ml_figures.html): common machine learning algorithms are listed, illustrated, and described.

[**About**](https://pdobrano25.github.io/ml_website/about.html): source code for analyses and a list of publications by Peter Dobranowski.