<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Predicting IBD using Metagenomic Data from Several Cohorts</title>

<script src="cmd_validation_files/header-attrs-2.29/header-attrs.js"></script>
<script src="cmd_validation_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="cmd_validation_files/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="cmd_validation_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="cmd_validation_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="cmd_validation_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="cmd_validation_files/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="cmd_validation_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="cmd_validation_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="cmd_validation_files/navigation-1.1/tabsets.js"></script>
<link href="cmd_validation_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="cmd_validation_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">



<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
<a class="navbar-brand" href="index.html"><img src="machomics_flat_white.png" alt="MachOmics" style="height:30px;"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="machomics.html">MachOmics</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Vignettes
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mlp_validation.html">Predicting Microbial Load (16S)</a>
    </li>
    <li>
      <a href="gevers_validation.html">Predicting Crohn&#39;s Disease (Metagenome)</a>
    </li>
    <li>
      <a href="cmd_validation.html">Predicting IBD (Metagenome)</a>
    </li>
    <li>
      <a href="sinai_validation.html">Predicting IBD (RNAseq)</a>
    </li>
    <li>
      <a href="metaaml_validation.html">Predicting Disease (Metagenome)</a>
    </li>
    <li>
      <a href="hmp_validation.html">Predicting IBD (Metabolome)</a>
    </li>
    <li>
      <a href="muller_validation.html">Predicting Metabolites (Metagenome)</a>
    </li>
    <li>
      <a href="litichevskiy_validation.html">Predicting Mouse Age (Metagenome)</a>
    </li>
  </ul>
</li>
<li>
  <a href="overfitcheck.html">Overfit Check</a>
</li>
<li>
  <a href="ml_figures.html">Machine Learning Models</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">




</div>


<style>
  .navbar-fixed-top { position: fixed; top: 0; width: 100%; z-index: 1000; }
  body { padding-top: 70px; }
</style>

<div id="header">



<h1 class="title toc-ignore">Predicting IBD using Metagenomic Data from
Several Cohorts</h1>

</div>


<p>The <a
href="https://waldronlab.io/curatedMetagenomicData/"><strong>curatedMetagenomicData</strong></a>
(<strong>CMD</strong>) is a large collection of microbiome datasets,
re-processed using a standard pipeline to minimize batch effects.</p>
<p>Ning et al. (2023) perform a <a
href="https://www.nature.com/articles/s41467-023-42788-0">meta-analysis</a>
of microbiome studies using the CMD to predict IBD from non-IBD
controls.</p>
<p>The authors apply <em>leave-one-cohort-out</em> (LOCO)
cross-validation to evaluate whether larger, multi-cohort datasets can
be used to predict IBD in a validation cohort.</p>
<p>Below, we attempt to validate their model and evaluate additional
models that may boost the performance.</p>
<p>Of note, only cohorts available in the CMD will be used.</p>
<div id="validating-the-analysis" class="section level1">
<h1><strong>Validating</strong> the analysis</h1>
<div id="loading-data" class="section level2">
<h2>Loading data</h2>
<p>CMD includes 3 out of 6 of the cohorts used in the study.</p>
<p>These include IBD and non-IBD stool microbiome samples from the Human
Microbiome Project 2 (“HMP”), LifelinesDeep (“LLD”), and Nielsen 2014
(“NIE”) cohorts.</p>
<p>Note: VilaAV_2018 was combined with LifelinesDeep in the
publication.</p>
<pre><code>##                  study_condition
## study_name        control  IBD
##   HMP_2019_ibdmdb      27  103
##   LifeLD_Vila        1135  355
##   NielsenHB_2014      236   82</code></pre>
<p>We can see some fairly large imbalances in the data sets. The authors
downsampled the larger class until the imbalance was closer to “1:2 to
1:3”. It appears that they performed this balancing once, and discarded
the rest of the data from the analyses thereafter.</p>
<p>Instead of doing this (because we can’t fully replicate their results
without knowing which samples they discarded), we will evaluate the
impact of balancing using an algorithm called <strong>SCUT</strong> <a
href="https://www.scitepress.org/Link.aspx?doi=10.5220/0005595502260234">(SMOTE
and Cluster-based Undersampling)</a>.</p>
<p>Ning used Random Forest, which we will use to evaluate LOCO AUC.</p>
</div>
</div>
<div id="helper-function" class="section level1">
<h1>Helper function</h1>
<p>First, let’s build a function that does the following:</p>
<ul>
<li><p>optionally re-balance the dataset using SCUT</p></li>
<li><p>train a model using 5x CV</p></li>
<li><p>use the model to predict the class of the held-out
dataset</p></li>
<li><p>calculate AUCs and plot ROC curves</p></li>
</ul>
</div>
<div id="should-we-rebalance" class="section level1">
<h1>Should we rebalance?</h1>
<p>Let’s compare the performance of an imbalanced data set with and
without hybrid up + down sampling (using SCUT).</p>
<p>The LifelinesDeep + VichVila datasets contain 1135 controls and 355
IBD samples, a ratio of 3:1. Let’s combine it with the HMP data to
evaluate the Nielsen data set.</p>
<p>Here is the ROC when using <em>unbalanced</em> data:</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/cmd_validation_files/figure-html/lld_hmp_unbalanced-1.png" width="672" /></p>
<p>Here is the ROC when using <em>balanced</em> data:</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/cmd_validation_files/figure-html/lld_hmp_balanced-1.png" width="672" /></p>
<p>Evidently, re-balancing achieves a comparable AUC with unremarkable
specificities and sensitivities, so it may not be necessary for this
dataset.</p>
<p>Now, let’s move on and evaluate the LOCO-CV AUCs for the other 2
datasets.</p>
<p>Here is the ROC curve when using the Lifelines + Nielsen data sets to
build a model, and the HMP data set to evaluate:</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/cmd_validation_files/figure-html/nie_lld-1.png" width="672" /></p>
<p>Here is the ROC curve when using the Nielson + HMP data sets to build
a model, and the Lifelines data set to evaluate:</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/cmd_validation_files/figure-html/nie_hmp-1.png" width="672" /></p>
<p>These AUCs are less impressive than what were originally published <a
href="https://www.nature.com/articles/s41467-023-42788-0/figures/2">See
Figure 2G</a>.</p>
</div>
<div id="performances" class="section level1">
<h1>Performances</h1>
<p>Nielsen was originally 0.780, but is 0.695 here. HMP was originally
0.713, but is 0.692 here. Lifelines was originally 0.843, but is 0.832
here.</p>
<p>I suspect this is because each of our training data sets are missing
3 additional cohorts! Without these data freely available, we cannot
fully replicate the authors’ results.</p>
<p>Nonetheless, we can extend this analysis to compare other machine
learning models.</p>
<div id="extending-the-analysis" class="section level2">
<h2><strong>Extending</strong> the analysis</h2>
<p>Let’s evaluate the LOCO performances using additional machine
learning algorithms.</p>
<pre class="r"><code># select models
ml.models = c(&quot;gbm&quot;,&quot;glmnet&quot;,&quot;ranger&quot;,&quot;svmLinear&quot;,&quot;svmRadial&quot;,&quot;xgbTree&quot;)</code></pre>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/cmd_validation_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p><em>Recall:</em> <em>HMP was originally 0.713.</em> <em>Lifelines was
originally 0.843.</em> <em>Nielsen was originally 0.780.</em></p>
<p>From these results, it appears that Random Forest is the best in 2 /
3 cohorts. Elastic net (glmnet) approaches the published AUC (0.780)
performance for the Nielsen data set.</p>
<p>However, I suspect that the AUCs in the Nielsen (NIE) are being
influenced by class imbalances, such that <em>sensitivities</em> are
high but <em>specificities</em> are low (or vice versa).</p>
<p>Let’s examine this suspicion by plotting the sensitivities and
specificities:</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/cmd_validation_files/figure-html/loop_sens-1.png" width="672" /></p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/cmd_validation_files/figure-html/loop_spec-1.png" width="672" /></p>
<p>Here, we see that where selected models had decent AUCs, the
specificity was higher and sensitivity was lower (and vice versa).</p>
<p>This illustrates the limitations of using imbalanced datasets and how
a single metric (e.g. AUC) can hide key performance attributes
(e.g. sensitivity). The study’s authors did not evaluate these metrics,
instead relying only on the composite AUC score to render
conclusions.</p>
</div>
</div>
<div id="conclusions" class="section level1">
<h1>Conclusions</h1>
<p>To conclude, I could not validate the performances of all 6 cohorts
included in the original study, and my re-analysis yielded lower
performances in the available 3 cohorts.</p>
<p>Importantly, AUCs in these data sets were sensitive to class
imbalances. Despite using hybrid sampling, sensitivities were quite
variable.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
