<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Predicting IBD using Metabolomes</title>

<script src="hmp_validation_files/header-attrs-2.29/header-attrs.js"></script>
<script src="hmp_validation_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="hmp_validation_files/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="hmp_validation_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="hmp_validation_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="hmp_validation_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="hmp_validation_files/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="hmp_validation_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="hmp_validation_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="hmp_validation_files/navigation-1.1/tabsets.js"></script>
<link href="hmp_validation_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="hmp_validation_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">



<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
<a class="navbar-brand" href="index.html"><img src="machomics_flat_white.png" alt="MachOmics" style="height:30px;"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="machomics.html">MachOmics</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Vignettes
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mlp_validation.html">Predicting Microbial Load (16S)</a>
    </li>
    <li>
      <a href="gevers_validation.html">Predicting Crohn&#39;s Disease (Metagenome)</a>
    </li>
    <li>
      <a href="cmd_validation.html">Predicting IBD (Metagenome)</a>
    </li>
    <li>
      <a href="sinai_validation.html">Predicting IBD (RNAseq)</a>
    </li>
    <li>
      <a href="metaaml_validation.html">Predicting Disease (Metagenome)</a>
    </li>
    <li>
      <a href="hmp_validation.html">Predicting IBD (Metabolome)</a>
    </li>
    <li>
      <a href="muller_validation.html">Predicting Metabolites (Metagenome)</a>
    </li>
    <li>
      <a href="litichevskiy_validation.html">Predicting Mouse Age (Metagenome)</a>
    </li>
  </ul>
</li>
<li>
  <a href="overfitcheck.html">Overfit Check</a>
</li>
<li>
  <a href="ml_figures.html">Machine Learning Models</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">




</div>


<style>
  .navbar-fixed-top { position: fixed; top: 0; width: 100%; z-index: 1000; }
  body { padding-top: 70px; }
</style>

<div id="header">



<h1 class="title toc-ignore">Predicting IBD using Metabolomes</h1>

</div>


<p><a href="https://huttenhower.sph.harvard.edu/home/">The Huttenhower
Lab</a> conducted one of the largest and deepest characterizations of
the IBD microbiome, incorporating metagenomics, metatranscriptomics, and
metabolomics. <a
href="https://www.nature.com/articles/s41564-018-0306-4">This study</a>
was published in Nature in 2019.</p>
<p>Their metabolomics data set has been reprocessed and uploaded by the
<a href="https://github.com/borenstein-lab">Borenstein lab</a>,
available <a
href="https://github.com/borenstein-lab/microbiome-metabolome-curated-data/tree/main/data/processed_data/FRANZOSA_IBD_2019">here</a>.
These data were incorporated in a <a
href="https://www.nature.com/articles/s41522-022-00345-5">meta-analysis</a>
of gut microbiome-metabolome associations.</p>
<p>Towards the end of Franzosa’s study, they use Random Forest to
classify IBD and non-IBD microbiomes using metabolites, achieving an AUC
of 0.92 using 5-fold cross-validation. Here, we attempt to validate this
results.</p>
<div id="validating-the-analysis" class="section level1">
<h1><strong>Validating</strong> the analysis</h1>
<div id="loading-data" class="section level2">
<h2>Loading data</h2>
<p>Let’s load the metabolite feature table and check the dimensions:</p>
<pre><code>## [1] &quot;220 samples by 8848 features&quot;</code></pre>
<p>Since the metabolomics were performed untargeted, most of the
features might not be annotated.</p>
<p>How many of the 8848 features were annotated?</p>
<pre><code>## [1] &quot;466 features are annotated (5%)&quot;</code></pre>
<p>Let’s keep just these 466 features, which is a good feature space for
machine learning, and renders a more interpretable conclusion when we
look for important features.</p>
<p>Now let’s check the sample data.</p>
<p>First, how many samples are in the original data set, and how many in
the external validation sets?</p>
<pre><code>##      dataset disease samples
## 1   Training      CD      68
## 2   Training Control      34
## 3   Training      UC      53
## 4 Validation      CD      20
## 5 Validation Control      22
## 6 Validation      UC      23</code></pre>
<p>We’ll be working with 34 control, 53 UC, and 68 CD samples to build
the model, which is a bit of an imbalance worth correcting for. It’s
made worse by the fact we’ll be pooling UC and CD together. The
validation dataset was originally nicely balanced between n=20-23 per
group, but these will also become imbalanced after pooling UC and
CD.</p>
<p>Lastly, let’s check for <a
href="https://pdobrano25.github.io/ml_website/overfitcheck.html#Pseudoreplicates">pseudoreplicates</a>:</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/hmp_validation_files/figure-html/check_pseudoreplicates-1.png" width="672" /></p>
<p>Great! There are no repeat samplings of any subject.</p>
</div>
<div id="data-processing" class="section level2">
<h2>Data processing</h2>
<p>Now we can check the feature distributions.</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/hmp_validation_files/figure-html/check_distributions-1.png" width="672" /></p>
<p>Based on the x axis scale, I suspect these data are profoundly
right-skewed and are asking to be log-transformed. Let’s see what
happens. We’ll also need to add a pseudocount because of the 0’s.</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/hmp_validation_files/figure-html/check_distributions_log-1.png" width="672" /></p>
<p>These look way better. Let’s move on to building our models and
validating them using internal CV.</p>
</div>
<div id="model-building" class="section level2">
<h2>Model building</h2>
<p>Franzosa employed 5x cross-validated random forest to predict IBD,
achieving an AUC of 0.92. The authors specify the following:</p>
<p><em>labels were randomly balanced before training and 100 trees were
considered</em></p>
<p>So, we’ll employ downsampling and specify 100 trees per random
forest.</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/hmp_validation_files/figure-html/randomforest_external_aucs-1.png" width="672" /></p>
<p>These values (0.903 and 0.910) are close to those reported in the
original study (0.92 and 0.89)</p>
<p>Now we can extend the analysis and apply additional models, under the
hypothesis that random forest was suboptimal for this data set.</p>
</div>
</div>
<div id="extending-the-analysis" class="section level1">
<h1><strong>Extending</strong> the analysis</h1>
<p>We’ll conduct 15 iterations of 5x CV and report AUCs from internal
and external data sets. We’ll continue to apply downsampling.</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/hmp_validation_files/figure-html/model_loop-1.png" width="672" /></p>
<p>All models are significantly superior to a model trained on null
data.</p>
<p>Random forest is slightly suboptimal for the internal validation, but
optimal for external validation, which suggests we’ve avoided
overfitting.</p>
<div id="feature-importances" class="section level2">
<h2>Feature importances</h2>
<p>Despite testing additional models, we haven’t learned anything new
from the data.</p>
<p>Instead, we can assess feature importances to see which metabolites
drive differences between IBD and controls.</p>
<p>Let’s go back to the originally trained model and extract feature
importances.</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/hmp_validation_files/figure-html/feature_importance-1.png" width="672" /></p>
<p>Interestingly, the most important feature for discriminating IBD from
controls was <em>urobilin</em>. Urobilin was found to be significantly
decreased in IBD in another <a
href="https://pmc.ncbi.nlm.nih.gov/articles/PMC10359577/">cohort</a> in
2023, and validated <a
href="https://gut.bmj.com/content/73/8/1392">again</a> by a separate
research group. Interestingly, reduced microbial bilirubin metabolism is
a marker of IBD and previous antibiotic use (<a
href="https://www.nature.com/articles/s41564-023-01549-x">source</a>).</p>
</div>
</div>
<div id="conclusions" class="section level1">
<h1>Conclusions</h1>
<p>To conclude, we were able to validate Franzosa’s metabolome-based IBD
classifier, seeing no significant improvement when using other machine
learning models. By extracting feature importances, we found urobilin to
be the top predictor of disease, which is highly accordant with the
literature.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
