<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Predicting Several Diseases using Metagenomic Data</title>

<script src="metaaml_validation_files/header-attrs-2.29/header-attrs.js"></script>
<script src="metaaml_validation_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="metaaml_validation_files/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="metaaml_validation_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="metaaml_validation_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="metaaml_validation_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="metaaml_validation_files/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="metaaml_validation_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="metaaml_validation_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="metaaml_validation_files/navigation-1.1/tabsets.js"></script>
<link href="metaaml_validation_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="metaaml_validation_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">



<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
<a class="navbar-brand" href="index.html"><img src="machomics_flat_white.png" alt="MachOmics" style="height:30px;"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="machomics.html">MachOmics</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Vignettes
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mlp_validation.html">Predicting Microbial Load (16S)</a>
    </li>
    <li>
      <a href="gevers_validation.html">Predicting Crohn&#39;s Disease (Metagenome)</a>
    </li>
    <li>
      <a href="cmd_validation.html">Predicting IBD (Metagenome)</a>
    </li>
    <li>
      <a href="sinai_validation.html">Predicting IBD (RNAseq)</a>
    </li>
    <li>
      <a href="metaaml_validation.html">Predicting Disease (Metagenome)</a>
    </li>
    <li>
      <a href="hmp_validation.html">Predicting IBD (Metabolome)</a>
    </li>
    <li>
      <a href="muller_validation.html">Predicting Metabolites (Metagenome)</a>
    </li>
    <li>
      <a href="litichevskiy_validation.html">Predicting Mouse Age (Metagenome)</a>
    </li>
  </ul>
</li>
<li>
  <a href="overfitcheck.html">Overfit Check</a>
</li>
<li>
  <a href="ml_figures.html">Machine Learning Models</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">




</div>


<style>
  .navbar-fixed-top { position: fixed; top: 0; width: 100%; z-index: 1000; }
  body { padding-top: 70px; }
</style>

<div id="header">



<h1 class="title toc-ignore">Predicting Several Diseases using
Metagenomic Data</h1>

</div>


<p><a href="http://segatalab.cibio.unitn.it/tools/metaml/index.html">The
Segata Lab</a> published a <a
href="https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004977">study</a>
in 2016 employing machine learning on microbiomes to predict various
diseases, including liver cirrhosis, colorectal cancer, IBD, obesity,
and type 2 diabetes.</p>
<p>The stool microbiome dataaset is available <a
href="https://github.com/SegataLab/metaml/tree/master/data">here</a>.</p>
<p>Below, we validate their findings and extend the analysis to employ
<strong>multiclass classification</strong> with
<strong>downsampling</strong>.</p>
<div id="validating-the-analysis" class="section level1">
<h1><strong>Validating</strong> the analysis</h1>
<div id="loading-data" class="section level2">
<h2>Loading data</h2>
<p>Let’s load the data and see what types of samples are included:</p>
<pre><code>##                       disease sample count
## 1                           -           20
## 2                           -            7
## 3                      cancer           48
## 4                   cirrhosis          118
## 5           ibd_crohn_disease           25
## 6      ibd_ulcerative_colitis          148
## 7  impaired_glucose_tolerance           49
## 8               large_adenoma           13
## 9                     leaness           89
## 10                          n          944
## 11                 n_relative           47
## 12                      obese            5
## 13                    obesity          164
## 14                 overweight           10
## 15              small_adenoma           26
## 16             stec2-positive           43
## 17                        t2d          223
## 18                underweight            1</code></pre>
<p>This is a little messy, so let’s clean up the samples into the
categories included in the study.</p>
</div>
<div id="metadata-processing" class="section level2">
<h2>Metadata processing</h2>
<pre><code>##     disease sample count
## 1    cancer           48
## 2 cirrhosis          118
## 3       IBD          173
## 4      none          944
## 5   obesity          164
## 6       t2d          223</code></pre>
<p>A small note: it’s unclear which categories of samples contributed to
the 981 control samples listed in the original study. I only see
944.</p>
<p>Let’s also check if there are sample duplicates:</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/metaaml_validation_files/figure-html/metadata_duplicates_1-1.png" width="672" /></p>
<p>Uh oh. That’s a notable number of <a
href="https://pdobrano25.github.io/ml_website/overfitcheck.html#Pseudoreplicates">pseudoreplicates</a>.
Which conditions do they belong to?</p>
<pre><code>##     disease &gt;1 replicate
## 1    cancer            0
## 2 cirrhosis            0
## 3       IBD           66
## 4      none          153
## 5   obesity            0
## 6       t2d            0</code></pre>
<p>Many of the controls were replicates, which we can spare. However, 66
/ 173 of the IBD samples were replicates, which we’d obviously rather
not spare. But, we need to if we want to apply machine learning without
blatantly overfitting. So, we’ll take only the first entry per
subject.</p>
<p>Here are the final tallies of samples after removing
pseudoreplicates.</p>
<pre><code>##     disease samples
## 1    cancer      48
## 2 cirrhosis     118
## 3       IBD     107
## 4      none     851
## 5   obesity     164
## 6       t2d     223</code></pre>
<p>Alright. Now let’s check the ratios of controls to cases per study
among studies of disease.</p>
<pre><code>##            disease
## studyID     cancer cirrhosis IBD none obesity t2d
##   22699609       0         0   0  115       0   0
##   25807110       0         0   0   35       0   0
##   25981789       0         0   0   38       0   0
##   cancer        48         0   0   47       0   0
##   cirrhosis      0       118   0  114       0   0
##   IBD            0         0 107  260       0   0
##   obesity        0         0   0   25     164   0
##   T2D            0         0   0  174       0 170
##   WT2D           0         0   0   43       0  53</code></pre>
<p>Every study of disease also included approximately as many, or more,
control samples as case samples.</p>
<p>Now let’s process the sequencing data.</p>
</div>
<div id="data-processing" class="section level2">
<h2>Data processing</h2>
<p>Let’s extract out the species data and check out the their
distributions.</p>
<pre><code>## [1] &quot;826 species remain.&quot;</code></pre>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/metaaml_validation_files/figure-html/data_processing_1-1.png" width="672" /></p>
<p>We should convert to relative abundance, log transform, and add a
pseudocount.</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/metaaml_validation_files/figure-html/data_processing_2-1.png" width="672" /></p>
<p>Log transforming improved the distributions to approximately normal,
but still right skewed. Nonetheless, it’s looking in acceptable shape to
continue on to building models.</p>
</div>
<div id="model-building" class="section level2">
<h2>Model building</h2>
<p>The authors approach their task in a number of ways:</p>
<p><em>Our multi-level validation strategy includes the assessment of
microbiome models on single cohorts, across stages of the same study,
across different studies, and across target outcomes and
conditions</em></p>
<p>I’m interested in validating <a
href="https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004977#pcbi.1004977.ref032">Fig
2</a>, where they calculate a variety of metrics including AUC, for each
of the datasets separately. Of note, they evaluate both Random Forest
and SVM models. For species-based models, the SVM used a radial basis
kernel.</p>
<p>Since they also mention evaluating elastic net, let’s go ahead
include it, and a few more models.</p>
<p>They also compared their models against null datasets, where the
class label was randomly shuffled. This is helpful to show,
statistically, superiority of their model to an empirical null
distribution.</p>
<p>So, we’ll do the following:</p>
<ul>
<li><p>For each of the 6 diseases/datasets:</p></li>
<li><p>Evaluate 5 machine learning algorithms,</p></li>
<li><p>Build models 15 times,</p></li>
<li><p>For both real and null data sets,</p></li>
<li><p>And extract the internal validation AUCs.</p></li>
</ul>
<p>Here are the results:</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/metaaml_validation_files/figure-html/model_building_1-1.png" width="672" /></p>
<p>This plot shows the distributions of 15 repeats of using real
(colored) data and null (grey) data to train each model. I ran t-tests
on each comparison followed by a Bonferroni adjustment to control the
false discovery rate. Significant values are indicated by a *.</p>
<p>Using the internal validation metrics, we can see that random forest
(ranger) is generally superior to SVM across datasets. Elastic net
(glmnet) is quite competitive with ranger.</p>
<p>We can also get a sense of how some diseases (e.g. obesity) are
harder to predict than others (e.g. IBD).</p>
<p>Importantly, most of these values are either as good or better than
those reported in the original study.</p>
<p>Let’s consider these results validated and move on to multiclass
machine learning.</p>
</div>
</div>
<div id="extending-the-analysis" class="section level1">
<h1><strong>Extending</strong> the analysis</h1>
<p>Above, we constructed 1 predictor for each disease. Depending on the
research question, it might be more ideal to build ONE model that can
report the probability a microbiome belongs to one of the diseases,
simultaneously. This is a task for a multiclass classifier.</p>
<div id="multiclass-classifier" class="section level2">
<h2>Multiclass Classifier</h2>
<p>First, we’ll build a multiclass random forest that handles all
samples simultaneously:</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/metaaml_validation_files/figure-html/multivariate_rf_conf-1.png" width="672" /></p>
<p>This confusion matrix illustrates a general low accuracy in
predicting each disease. That is, the values in parentheses along the
diagonal tiles (from bottom left to top right) are quite low for most
diseases. The model is predicting most microbiomes belong to healthy
individuals.</p>
<p>I suspect the large class imbalance (e.g. n=665 “none” vs n=48
“cancer”) is causing the model to bias its prediction towards the
overrepresented class.</p>
<p>What do the ROC curves look like?</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/metaaml_validation_files/figure-html/multivariate_rf_auc-1.png" width="672" /></p>
<p>This ROC curve seems to suggest all diseases are being predicted
reasonably well. However, “none” is predicted the poorest, likely
because of the high degree of false positives observed in the confusion
matrix.</p>
</div>
<div id="downsample" class="section level2">
<h2>Downsample</h2>
<p>To eliminate the class imbalance, let’s downsample these data down to
the smallest dataset (n=48). I suspect this will sacrifice accuracy,
while improving the false positive rate.</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/metaaml_validation_files/figure-html/multivariate_rf_conf_balanced-1.png" width="672" /></p>
<p>This looks considerably better. The values in parentheses along the
diagonal indicate that each disease is being predicted much better.</p>
<p>Let’s see the ROC curves:</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/metaaml_validation_files/figure-html/multivariate_rf_auc_balanced-1.png" width="672" /></p>
<p>Once again, these ROC curves seem to suggest all diseases are being
predicted at least reasonably well. We see that the AUC has shrunk by
~5%. We also see that the model performs most poorly with “none” and
“t2d”, in agreement with the confusion matrix.</p>
</div>
</div>
<div id="conclusions" class="section level1">
<h1>Conclusions</h1>
<p>To conclude, we found that microbiome-based classifiers could predict
disease quite well, particularly when control samples were confined to
each study.</p>
<p>When we built a model that tries to predict all diseases at once, we
found that classification specificities and sensitivities suffered from
large class imbalances. This illustrates the trade-offs of balancing
datasets when considering class-specific accuracies.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
