<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Predicting Metabolites using Metagenome Compositions</title>

<script src="muller_validation_files/header-attrs-2.29/header-attrs.js"></script>
<script src="muller_validation_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="muller_validation_files/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="muller_validation_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="muller_validation_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="muller_validation_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="muller_validation_files/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="muller_validation_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="muller_validation_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="muller_validation_files/navigation-1.1/tabsets.js"></script>
<link href="muller_validation_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="muller_validation_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">



<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
<a class="navbar-brand" href="index.html"><img src="machomics_flat_white.png" alt="MachOmics" style="height:30px;"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="machomics.html">MachOmics</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Vignettes
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mlp_validation.html">Predicting Microbial Load (16S)</a>
    </li>
    <li>
      <a href="gevers_validation.html">Predicting Crohn&#39;s Disease (Metagenome)</a>
    </li>
    <li>
      <a href="cmd_validation.html">Predicting IBD (Metagenome)</a>
    </li>
    <li>
      <a href="sinai_validation.html">Predicting IBD (RNAseq)</a>
    </li>
    <li>
      <a href="metaaml_validation.html">Predicting Disease (Metagenome)</a>
    </li>
    <li>
      <a href="hmp_validation.html">Predicting IBD (Metabolome)</a>
    </li>
    <li>
      <a href="muller_validation.html">Predicting Metabolites (Metagenome)</a>
    </li>
    <li>
      <a href="litichevskiy_validation.html">Predicting Mouse Age (Metagenome)</a>
    </li>
  </ul>
</li>
<li>
  <a href="overfitcheck.html">Overfit Check</a>
</li>
<li>
  <a href="ml_figures.html">Machine Learning Models</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">




</div>


<style>
  .navbar-fixed-top { position: fixed; top: 0; width: 100%; z-index: 1000; }
  body { padding-top: 70px; }
</style>

<div id="header">



<h1 class="title toc-ignore">Predicting Metabolites using Metagenome
Compositions</h1>

</div>


<p>The <a href="https://github.com/borenstein-lab">Borenstein lab</a>
published a <a
href="https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-021-01149-z">study</a>
seeking to predict metabolites in stool microbiomes using genus-level
microbe abundances. This is not the first attempt at a research group
trying to tackle this problem, <a
href="https://www.nature.com/articles/s41467-019-10927-1">(for
example)</a>, but the Borenstein group did great work collating several
datasets made readily available for others to use.</p>
<p>At a simple level, Muller’s study built machine learning (random
forest) regression algorithms, using relative abundances of genera to
predict the abundances of metabolites shared across datasets. They did
additional analyses (e.g. random-effects models) to assess the
generalizability of predictions across datasets. I am interested in
simply seeing if bacterial abundances can predict metabolites, and
whether additional models can outperform random forest.</p>
<p>Below, I focus on only 2 of the datasets Muller studied: FRANZOSA and
IHMP. Both of these datasets employ <em>whole genome shotgun
sequencing</em> and <em>untargeted metabolomics</em> on IBD microbiomes.
Below, I will:</p>
<ul>
<li><p>Build models using FRANZOSA’s n=164 samples</p></li>
<li><p>Evaluate the predictions on the IHMP’s n=79 samples</p></li>
<li><p>Test additional models that improve the predictive
power.</p></li>
<li><p>Extract feature importances and identify bacteria associated with
metabolites</p></li>
</ul>
<div id="validating-the-analysis" class="section level1">
<h1><strong>Validating</strong> the analysis</h1>
<div id="loading-metadata" class="section level2">
<h2>Loading metadata</h2>
<p>First, we’ll select the samples we want to work with. We already know
there are <a
href="https://pdobrano25.github.io/ml_website/overfitcheck.html#Pseudoreplicates">pseudoreplicates</a>
in the raw datasets, so let’s select only unique IBD patients to work
with:</p>
<pre><code>##             dataset disease samples
## 1 FRANZOSA_IBD_2019     IBD     164
## 2  iHMP_IBDMDB_2019     IBD      79</code></pre>
<p>There are 164 unique subjects’ samples in the Franzosa dataset, and
79 in the IHMP dataset.</p>
</div>
<div id="loading-metabolomic-data" class="section level2">
<h2>Loading metabolomic data</h2>
<p>Now, we’ll load both metabolomic datasets and restrict to annotated
metabolites shared in each dataset.</p>
<pre><code>## [1] &quot;Franzosa contains 164 samples by 8,848 metabolites (467 annotated)&quot;</code></pre>
<pre><code>## [1] &quot;IHMP contains 79 samples by 81,867 metabolites (597 annotated)&quot;</code></pre>
<pre><code>## [1] &quot;238 intersecting metabolites&quot;</code></pre>
<p>We’ll check the distributions of the datasets.</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/muller_validation_files/figure-html/distribution_check_mbx-1.png" width="672" /></p>
<p>Log-transforming the data with an added pseudocount had the effect we
expected.</p>
</div>
<div id="loading-metagenomic-data" class="section level2">
<h2>Loading metagenomic data</h2>
<p>Now we can load the metagenomic data, and as with the metabolites,
we’ll take the intersecting species.</p>
<p>We’re going to need to apply some stringent prevalence and abundance
filtering.</p>
<p>Let’s see how many taxa remain across various thresholds.</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/muller_validation_files/figure-html/metagenomic_filtering_plot-1.png" width="672" /></p>
<p>As we can see, we can preserve a little over 300 taxa if we apply a
filter that keeps taxa “detected at 0.01% abundance in 10%+ samples”</p>
<p>Let’s apply that filter and keep the intersecting (shared) taxa
between datasets.</p>
<pre><code>## [1] &quot;355 taxa remain that are shared with IHMP&quot;</code></pre>
<p>Excellent. 355 taxa is a reasonable number to perform this analysis
on.</p>
<p>Now let’s assess the distributions of taxa and log-transform if
necessary, applying a single pseudocount to both datasets.</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/muller_validation_files/figure-html/distribution_check_mgx-1.png" width="672" /></p>
<p>Log-transforming improved the distributions of taxa in both
datasets.</p>
</div>
<div id="building-models" class="section level2">
<h2>Building models</h2>
<p>Our objective is to predict the abundance of each metabolite using
the taxa abundances.</p>
<p>I’m going to write a function that performs the following:</p>
<ul>
<li><p>Selects one metabolite (from the Franzosa dataset)</p></li>
<li><p>Builds a model that predicts the metabolite’s abundance using
taxa abundances (using the Franzosa dataset). We’re going to use random
forest <strong>OOB predictions</strong>, which are as robust as
multi-fold cross-validation, but <strong>blazingly</strong>
faster.</p></li>
<li><p>Builds a model that predicts scrambled (null) metabolite
abundances</p></li>
<li><p>Records the Spearman correlation of predictions from internal
validation samples</p></li>
<li><p>Applies the model to the IHMP dataset, and records the Spearman
correlation coefficient</p></li>
</ul>
<p>And repeat this process across all metabolites</p>
<pre><code>## [1] &quot;41 metabolites with a Spearman rho &gt; 0.3&quot;</code></pre>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/muller_validation_files/figure-html/ranger_plot-1.png" width="672" /></p>
<p>Here, I’ve plotted the metabolites with a Spearman correlation
coefficient above 0.3 using the external evaluation (IHMP) dataset.
Results from the internal data are in red, while external data are in
blue. Null performances (built and evaluated using internal and external
data) are in grey. All models were built and evaluated 15 times.</p>
<p>The authors used a threshold of 0.3 as well, but added additional
statistical validation for their definition of a metabolite that can be
robustly predicted.</p>
<p>Note: the original study used only healthy microbiomes to build
predictors, whereas I am focusing on IBD microbiomes. Despite this key
difference, I’ve nonetheless validated that <em>urobilin</em> can be
well predicted. Interestingly, this metabolite is also useful for
discriminating healthy from IBD microbiomes, as I showed <a
href="https://pdobrano25.github.io/ml_website/hmp_validation.html#Feature_importances">here</a>.</p>
</div>
</div>
<div id="extending-the-analysis" class="section level1">
<h1><strong>Extending</strong> the analysis</h1>
<p>Now, we’ll ask whether other machine learning models are superior to
random forest. The authors also evaluated lasso and elastic net. To save
on computation time, I’m going to limit this benchmark to metabolites
with external validation Spearman correlations &gt; 0.3. We’re also
going to drop the null tests, since our goal is to evaluate whether
these other models outperform random forest.</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/muller_validation_files/figure-html/model_plots-1.png" width="672" /></p>
<p>It doesn’t appear like anything is superior to random forest. Let’s
test this statistically using a mixed effects model.</p>
<pre class="r"><code># set Random Forest (ranger) as the reference group
muller_loop_output$model = factor(muller_loop_output$model, levels=c(&quot;ranger&quot;, &quot;gbm&quot;, &quot;glmnet&quot;, &quot;svmLinear&quot;, &quot;svmRadial&quot;, &quot;xgbTree&quot;))

# build a mixed effects regression model
lmerTest::lmer(external_real_spearman ~ model + (1|metabolite), muller_loop_output) %&gt;%
  summary() %&gt;% coef()</code></pre>
<pre><code>##                    Estimate  Std. Error         df    t value      Pr(&gt;|t|)
## (Intercept)     0.378583693 0.011151587   44.02096  33.948862  3.284385e-33
## modelgbm       -0.058653410 0.003736449 3644.00000 -15.697636  8.741438e-54
## modelglmnet    -0.020449873 0.003736449 3644.00000  -5.473078  4.721136e-08
## modelsvmLinear -0.136274861 0.003736449 3644.00000 -36.471761 1.495995e-248
## modelsvmRadial -0.006595381 0.003736449 3644.00000  -1.765147  7.762279e-02
## modelxgbTree   -0.097983469 0.003736449 3644.00000 -26.223690 5.341538e-139</code></pre>
<p>The mixed effects model shows random forest is significantly superior
(across all metabolites), except for svmRadial.</p>
<p>Now, we sort of biased these results by selecting the top metabolites
(ρ &gt; 0.3) identified by random forest. It’s entirely possible that
other models could have identified <strong>different</strong>
metabolites better than random forest, which could have bumped up their
overall performance. However, these 41 metabolites alone took 9 hours to
compute.</p>
<div id="feature-importances" class="section level2">
<h2>Feature importances</h2>
<p>Since random forest was superior, let’s go back to the first models
we built using the ranger package. We’ll extract out the feature
importances for metabolites and correlate them with the taxa to identify
their direction of association.</p>
<p>Let’s plot a heatmap with features (taxa) and their associations with
the top 41 metabolites.</p>
<p>We’ll select only the top 20 taxa based on their mean importance
value.</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/muller_validation_files/figure-html/feature_heatmap-1.png" width="672" /></p>
<p>There are a few metabolites with an feature importances worth
noting.</p>
<p>First, <strong>urobilin</strong>, which I previously found to be
associated with IBD microbiomes <a
href="https://pdobrano25.github.io/ml_website/hmp_validation.html#Feature_importances">here</a>.
Urobilin has a few features with outsized importance values towards the
top right of the heatmap.</p>
<p>Second, <strong>chenodeoxycholate</strong> (CDCA), a primary bile
acid, has a band of importance features. Primary bile acids, including
CDCA, have been consistently found to be enriched in IBD, including in
Franzosa’s original <a
href="https://www.nature.com/articles/s41564-018-0306-4">study</a>.</p>
<p>Let’s explore the features most strongly predictive of these two
metabolites</p>
<p><img src="/Users/peter/Documents/PhD/ml_website/docs/muller_validation_files/figure-html/feature_plot-1.png" width="672" /></p>
<p>For <strong>urobilin</strong>, we see <em>Holdemania</em> is most
strongly associated and predictive feature.</p>
<p>For <strong>CDCA</strong>, several taxa are negatively associated,
including <em>Angelakisella</em>, <em>Pullichristensenella</em>, and an
unclassified species annotated as <em>UBA866.</em> I’m unfamiliar with
these taxa names.</p>
<p><a
href="https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1871018"><em>Angelakisella</em></a>
is a genus in the Oscillospiraceae family. <a
href="https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&amp;id=1952448&amp;lvl=6&amp;lin=f&amp;keep=1&amp;srchmode=5&amp;unlock&amp;filter=genome_filter"><em>UBA866</em></a>
is annotated as a Ruminococcaceae. <a
href="https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&amp;id=3097446&amp;lvl=3&amp;keep=1&amp;srchmode=1&amp;unlock"><em>Pullichristensenella</em></a>
is a candidatus (proposed, but not yet accepted) annotation for a genus
in the Clostridia incertae sedis family.</p>
</div>
</div>
<div id="conclusions" class="section level1">
<h1>Conclusions</h1>
<p>To conclude, we were able to predict <em>some</em> metabolite
abundances using genus-level metagenomic data in a cohort of IBD
patients. We employed a separate cohort to validate these
predictions.</p>
<p>We found that random forest was superior (or at least non-inferior)
to the other models.</p>
<p>We identified specific taxa that are predictive of certain
metabolites, like urobilin and CDCA, which are relevant to IBD.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
